language: node_js
node_js:
  # TODO: Run Babel on tests so that async-await works in Node 6
  # - '6'
  - '8'
cache: yarn
script: 
  - yarn 
  - yarn run start
sudo: false
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "rongfengliang"
      - git config --local user.email "1141591465@qq.com"
deploy:
  provider: releases
  api_key: "728f945c30e82ab4cf20ffe470de3dad8cb50b9b"
  file: dist/*
  skip_cleanup: true
  branches:
    only:
    - master
